### ISSUE TITLE
게시판 관련 API 작성 요청

### ISSUE THREAD

**Issue by jini814** [subbni/lettrip-web#51]
1. 게시판 목록(ArticleList)에서 제목 옆에 댓글 수 보이는 기능
ex. 제목 (2) 이런식으로 articlelist에서 글 목록 불러올 때 가져오는 정보에서 댓글 수 추가해주시면 될 것 같습니다.

2. 게시글 좋아요 기능
-> 여행 코스 좋아요 및 장소 검색 좋아요 기능처럼 좋아요 눌러서
기존에 있던 likecount가 올라가면 페이지 내에서도 보이게 설정하고
마이 페이지에서도 확인할 수 있도록 추가하면 좋을 것 같습니다.

(+저만 이상한 건지 모르겠는데 마이페이지 접근 시 바로 오류가 생겨버리네요 그래서 새로 코드 다운도 받아봤는데 똑같아서 한번 확인 부탁드려요)

**Comment by subbni** [comment]
[ ] 게시글 목록 리스트에 댓글 카운트 추가
[ ] 게시글 좋아요 기능
